-- ==========================================
-- AutoBell SaaS Database Schema (Supabase)
-- ==========================================

-- 1. Organizations (Schools/Factories)
create table organizations (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  address text,
  subscription_status text default 'active', -- 'active', 'trial', 'expired'
  created_at timestamp with time zone default now()
);

-- 2. User Profiles (Linked to Supabase Auth)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  org_id uuid references organizations(id),
  role text default 'admin', -- 'super_admin', 'school_admin', 'viewer'
  full_name text,
  created_at timestamp with time zone default now()
);

-- 3. Devices (The ESP32 Controllers)
create table devices (
  id uuid default gen_random_uuid() primary key,
  org_id uuid references organizations(id) on delete cascade not null,
  mac_address text unique not null,
  name text not null, -- e.g., "Main Building Bell"
  api_key text default encode(gen_random_bytes(16), 'hex'), -- Secret for ESP32 to authenticate
  is_online boolean default false,
  last_heartbeat timestamp with time zone,
  timezone_offset integer default 0, -- Minutes from UTC
  created_at timestamp with time zone default now()
);

-- 4. Schedules (Bell Times)
create table schedules (
  id uuid default gen_random_uuid() primary key,
  device_id uuid references devices(id) on delete cascade not null,
  bell_time time not null, -- e.g., 08:30:00
  label text, -- e.g., "Morning Assembly"
  days_of_week integer[] default '{1,2,3,4,5}', -- 1=Mon, 7=Sun
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- 5. Command Queue (For Real-time Actions like 'RING NOW')
create table command_queue (
  id bigint generated by default as identity primary key,
  device_id uuid references devices(id) on delete cascade not null,
  command text not null, -- 'RING', 'REBOOT', 'SYNC_TIME'
  payload jsonb default '{}'::jsonb, -- Extra params
  status text default 'pending', -- 'pending', 'executed', 'failed'
  created_at timestamp with time zone default now()
);

-- ==========================================
-- Security Policies (Row Level Security)
-- ==========================================

-- Enable RLS
alter table organizations enable row level security;
alter table profiles enable row level security;
alter table devices enable row level security;
alter table schedules enable row level security;
alter table command_queue enable row level security;

-- Policies (Simplified for overview)
-- 1. Users can only see data for their own Organization
create policy "Users see own org" on organizations
  for select using (id in (select org_id from profiles where profiles.id = auth.uid()));

create policy "Users see own devices" on devices
  for all using (org_id in (select org_id from profiles where profiles.id = auth.uid()));

create policy "Users manage own schedules" on schedules
  for all using (device_id in (select id from devices where org_id in (select org_id from profiles where profiles.id = auth.uid())));

-- 2. ESP32 Access (via API Key or specialized auth)
-- Note: For ESP32, we usually use a Service Role or a specialized RPC function to bypass RLS safely
-- or we create a specific policy if we map API Keys to users.
-- For simplicity in this iteration, we will use a "public" API for devices with a strict verify function.

-- ==========================================
-- Database Functions (API Endpoints for ESP32)
-- ==========================================

-- Function for ESP32 to fetch its config
-- Call via RPC: supabase.rpc('get_device_config', { 'device_mac': '...' })
create or replace function get_device_config(device_mac text)
returns json as $$
declare
  target_device_id uuid;
  schedule_data json;
begin
  -- 1. Find Device
  select id into target_device_id from devices where mac_address = device_mac;
  
  if target_device_id is null then
    return json_build_object('error', 'Device not found');
  end if;

  -- 2. Update Heartbeat
  update devices set last_heartbeat = now(), is_online = true where id = target_device_id;

  -- 3. Get Schedules
  select json_agg(t) into schedule_data from (
    select bell_time, days_of_week from schedules 
    where device_id = target_device_id and is_active = true
  ) t;

  return json_build_object(
    'status', 'ok',
    'schedules', coalesce(schedule_data, '[]'::json)
  );
end;
$$ language plpgsql security definer;

-- Function for ESP32 to poll pending commands
create or replace function poll_commands(device_mac text)
returns json as $$
declare
  target_device_id uuid;
  cmd_record record;
begin
  select id into target_device_id from devices where mac_address = device_mac;
  
  if target_device_id is null then
    return json_build_object('error', 'Device not found');
  end if;

  -- Update Heartbeat
  update devices set last_heartbeat = now(), is_online = true where id = target_device_id;

  -- Get oldest pending command
  select * into cmd_record from command_queue 
  where device_id = target_device_id and status = 'pending'
  order by created_at asc limit 1;

  if cmd_record.id is not null then
    -- Mark as executing/executed to prevent double pull
    update command_queue set status = 'executed' where id = cmd_record.id;
    
    return json_build_object(
      'has_command', true,
      'command', cmd_record.command,
      'payload', cmd_record.payload
    );
  else
    return json_build_object('has_command', false);
  end if;
end;
$$ language plpgsql security definer;
