[platformio]
default_envs = esp32_s3

[env:esp32_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
build_src_filter = +<main_s3.cpp>
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DINPUT_VOLTAGE_ADC_PIN=3
    -DINPUT_VOLTAGE_DIVIDER_RATIO=2.0
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    tzapu/WiFiManager @ ^2.0.17
    adafruit/RTClib @ ^2.1.4
    https://github.com/schreibfaul1/ESP32-audioI2S.git#2.0.6
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
