
-- Create command_queue table for device commands
CREATE TABLE IF NOT EXISTS public.command_queue (
    id bigint generated by default as identity primary key,
    device_id uuid REFERENCES public.bell_devices(id) ON DELETE CASCADE NOT NULL,
    command text NOT NULL, -- 'RING', 'REBOOT', 'SYNC_TIME', 'CONFIG'
    payload jsonb DEFAULT '{}'::jsonb,
    status text DEFAULT 'pending', -- 'pending', 'executed', 'failed'
    created_at timestamp with time zone DEFAULT now(),
    executed_at timestamp with time zone
);

-- Enable RLS
ALTER TABLE public.command_queue ENABLE ROW LEVEL SECURITY;

-- Policies

-- Users can view commands for devices in their school
CREATE POLICY "Users can view commands in their school" ON public.command_queue
    FOR SELECT
    USING (
        device_id IN (
            SELECT id FROM public.bell_devices WHERE school_id = get_my_school_id()
        )
    );

-- Users can insert commands for devices in their school
CREATE POLICY "Users can insert commands in their school" ON public.command_queue
    FOR INSERT
    WITH CHECK (
        device_id IN (
            SELECT id FROM public.bell_devices WHERE school_id = get_my_school_id()
        )
    );

-- Devices can view their own pending commands
-- Assuming devices authenticate and have a claim or we use a function (as seen in database_schema.sql)
-- For now, if using RLS directly with device auth:
CREATE POLICY "Devices can view own commands" ON public.command_queue
    FOR SELECT
    USING (
        device_id IN (
            SELECT id FROM public.bell_devices 
            WHERE mac_address = (auth.jwt() ->> 'mac_address')
        )
    );

-- Devices can update their own commands (to mark as executed)
CREATE POLICY "Devices can update own commands" ON public.command_queue
    FOR UPDATE
    USING (
        device_id IN (
            SELECT id FROM public.bell_devices 
            WHERE mac_address = (auth.jwt() ->> 'mac_address')
        )
    );
